os:
  - linux
  - osx

sudo: required
dist: bionic

env:
  global:
    - BUILD_DIR=./build/Release
    - ELECTRON_VER=12.2.3
    - VLC_VER=2.8.8.

  matrix:
    - npm_config_wcjs_runtime_version=$ELECTRON_VER npm_config_wcjs_runtime=electron npm_config_wcjs_arch=x64

addons:
  apt:
    packages:
    - libvlc-dev

before_install:
  - git submodule update --init --recursive
  - ./travis_before_install.sh
  - if [[ "$npm_config_wcjs_runtime" = "electron" && "$npm_config_wcjs_runtime_version" = "latest" ]]; then export npm_config_wcjs_runtime_version=`npm show electron version`; fi
  - export WCJS_ARCHIVE=WebChimera.js_${npm_config_wcjs_runtime}_${npm_config_wcjs_runtime_version}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.zip
  - export WCJS_ARCHIVE_PATH=$BUILD_DIR/$WCJS_ARCHIVE
  - export WCJS_FULL_ARCHIVE=WebChimera.js_${TRAVIS_TAG}_${npm_config_wcjs_runtime}_v${npm_config_wcjs_runtime_version}_VLC_v${VLC_VER}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.tar.gz
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export WCJS_FULL_ARCHIVE_PATH=$BUILD_DIR/$WCJS_FULL_ARCHIVE; else export WCJS_FULL_ARCHIVE_PATH=$WCJS_ARCHIVE_PATH; fi

script:
  - npm install
#  - npm install yarn
#  - ./node_modules/.bin/yarn

before_deploy: ./travis_before_deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN

  file:
    - $WCJS_FULL_ARCHIVE_PATH
    - $WCJS_ARCHIVE_PATH

  skip_cleanup: true

  on:
    repo: mZer0ne/WebChimera.js
    tags: true
