os:
  - linux
  - osx

dist: bionic
sudo: required

env:
  global:
    - BUILD_DIR=./build/Release
    - ELECTRON_VER=latest
    - VLC_VER=3.0.17.3

  matrix:
    - npm_config_wcjs_runtime_version=$ELECTRON_VER npm_config_wcjs_runtime=electron npm_config_wcjs_arch=x64

addons:
  apt:
    packages:
    - libvlc-dev

before_install:
  - git submodule update --init --recursive
  - ./travis_before_install.sh
  - if [[ "$npm_config_wcjs_runtime" = "electron" && "$npm_config_wcjs_runtime_version" = "latest" ]]; then export npm_config_wcjs_runtime_version=`npm show electron version`; fi
  - if [[ "$npm_config_wcjs_runtime" = "nw" && "$npm_config_wcjs_runtime_version" = "latest" ]]; then export npm_config_wcjs_runtime_version=`npm show nw version`; fi
  - export WCJS_ARCHIVE=WebChimera.js_${npm_config_wcjs_runtime}_${npm_config_wcjs_runtime_version}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.zip
  - export WCJS_ARCHIVE_PATH=$BUILD_DIR/$WCJS_ARCHIVE
  - export WCJS_FULL_ARCHIVE=WebChimera.js_${TRAVIS_TAG}_${npm_config_wcjs_runtime}_v${npm_config_wcjs_runtime_version}_VLC_v${VLC_VER}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.tar.gz
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export WCJS_FULL_ARCHIVE_PATH=$BUILD_DIR/$WCJS_FULL_ARCHIVE; else export WCJS_FULL_ARCHIVE_PATH=$WCJS_ARCHIVE_PATH; fi

script: npm install

before_deploy: ./travis_before_deploy.sh

deploy:
  provider: releases

  api_key:
    secure: "CpczsCQyturCY0lpGL3EByp4KbIpWSJRO8mL1MP7TK809AYnSCebyCo4KxTdCTLcYagm97FKIhveezPcr68oGpWUJSbXPO/4eFmHEcdlcRYcS3uggaX2wU1NoDsBvtx2TrZ48hdqwlAKRlh3Umru9gvHfq8B+Mze0lSFZm393wMNe5sj3q+Jk2RExppXW6J3RYLgtFm5w/JpNFv4yFqWLSr0wManuaTZJoMpOZMdhEU03og0IT4nSoggWwA9a84SJnmzX9kTENT25c58HvPFtHKLTCdlrdHuNJ6AGhHLyAyQZgvhC0wNWfhoP1YuHpAv6SuH5a9mymQ9/K8jNj7A2IFppJuMUQFTlZZxRn6u7xtbT964O5GOEXgvidsxe8eieQFDZVXhv1rhOS7Lu5ZcD5T7qeH24AJMa0CDsh9no/xYaAUlG1p2o5qpIW8sZnb3fn299smFZi/d5KzldB4wEbTwG3e4W/zGz7cQUoJt8s9ODOki4rPxjs4jUQovbEocwAmoLKl9mCMTi0BENGkdDfT6WbD9p1ic2w1B1fDCdsNCf0GaIyn2Qg26uNz1tnVPUShkcrbJFsVEsmT7HqEyIg4bBQtse0c4kKnBIdzFbUATsNko9+slx4Vg31xAkBXTfI2n7Fc1NkgAf/xfdY5GCNXPNic05V6SSMkAp2R3Rcw="

  file:
    - $WCJS_ARCHIVE_PATH
    - $WCJS_FULL_ARCHIVE_PATH

  skip_cleanup: true

  on:
    repo: mZer0ne/WebChimera.js
    tags: true
