os:
#  - linux
  - osx

dist: bionic
sudo: required

env:
  global:
    - BUILD_DIR=./build/Release
    - ELECTRON_VER=latest
    - VLC_VER=3.0.17.3

  matrix:
    - npm_config_wcjs_runtime_version=$ELECTRON_VER npm_config_wcjs_runtime=electron npm_config_wcjs_arch=x64

addons:
  apt:
    packages:
    - libvlc-dev

before_install:
  - git submodule update --init --recursive
  - ./travis_before_install.sh
  - if [[ "$npm_config_wcjs_runtime" = "electron" && "$npm_config_wcjs_runtime_version" = "latest" ]]; then export npm_config_wcjs_runtime_version=`npm show electron version`; fi
  - export WCJS_ARCHIVE=WebChimera.js_${npm_config_wcjs_runtime}_${npm_config_wcjs_runtime_version}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.zip
  - export WCJS_ARCHIVE_PATH=$BUILD_DIR/$WCJS_ARCHIVE
  - export WCJS_FULL_ARCHIVE=WebChimera.js_${TRAVIS_TAG}_${npm_config_wcjs_runtime}_v${npm_config_wcjs_runtime_version}_VLC_v${VLC_VER}_${npm_config_wcjs_arch}_${TRAVIS_OS_NAME}.tar.gz
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export WCJS_FULL_ARCHIVE_PATH=$BUILD_DIR/$WCJS_FULL_ARCHIVE; else export WCJS_FULL_ARCHIVE_PATH=$WCJS_ARCHIVE_PATH; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn install

before_deploy: ./travis_before_deploy.sh

deploy:
  provider: releases
  api_key: "5d50e1f94f5403c86894728bb0a1f2137b362ae1"

  file:
    - $WCJS_FULL_ARCHIVE_PATH
    - $WCJS_ARCHIVE_PATH

  skip_cleanup: true

  on:
    repo: mZer0ne/WebChimera.js
    tags: true
